import { defineConfig } from "tsup";

export default defineConfig([
  // Main library bundles
  {
    entry: ["src/index.ts"],
    format: ["cjs", "esm"],
    dts: true,
    splitting: false,
    sourcemap: true,
    clean: true,
    bundle: true,
    minify: false,
    treeshake: true,
    // Bundle all workspace dependencies
    noExternal: [
      "@openfarm/core",
      "@openfarm/types",
      "@openfarm/logger",
      "@openfarm/result",
      "@openfarm/utils",
      "@openfarm/config",
      "@openfarm/agent-runner",
      "@openfarm/workflow-engine",
      "@openfarm/analysis",
      "@openfarm/coding-engines",
      "@openfarm/git-adapter",
      "@openfarm/github-adapter",
      "@openfarm/azure-adapter",
      "@openfarm/context",
    ],
    // Keep external npm dependencies external
    external: [
      "better-sqlite3",
      "pino",
      "pino-pretty",
      "uuid",
      "zod",
      "js-yaml",
      "ai",
      // External providers are optional and loaded dynamically
      "@openfarm/provider-opencode",
      "@openfarm/provider-aider",
      "@openfarm/provider-claude",
    ],
    outDir: "dist",
    target: "node18",
  },
  // CLI bundle (ESM for Ink compatibility)
  {
    entry: ["src/cli.ts"],
    format: ["esm"],
    splitting: false,
    sourcemap: true,
    bundle: true,
    minify: false,
    treeshake: true,
    noExternal: [
      "@openfarm/core",
      "@openfarm/types",
      "@openfarm/logger",
      "@openfarm/result",
      "@openfarm/utils",
      "@openfarm/config",
      "@openfarm/agent-runner",
      "@openfarm/workflow-engine",
      "@openfarm/analysis",
      "@openfarm/coding-engines",
      "@openfarm/git-adapter",
      "@openfarm/github-adapter",
      "@openfarm/azure-adapter",
      "@openfarm/context",
    ],
    external: [
      "better-sqlite3",
      "pino",
      "pino-pretty",
      "uuid",
      "zod",
      "js-yaml",
      "ai",
      // External providers are optional and loaded dynamically
      "@openfarm/provider-opencode",
      "@openfarm/provider-aider",
      "@openfarm/provider-claude",
    ],
    outDir: "dist",
    target: "node18",
    outExtension: () => ({ js: ".mjs" }),
  },
]);
